### ISSUE TITLE
Podcasts missing from new blog

### ISSUE THREAD

**Issue by df07** [StackExchange/stack-blog#138]
As reported on meta:

http://meta.stackexchange.com/questions/260958/podcasts-missing-from-new-blog

**Comment by donkirkby** [comment]
The post on meta seems to only be talking about really old episodes that aren't on SoundCloud. I just found that the new episodes aren't attached correctly either. I just tried to download using AntennaPod on Android, and it treats them like a text post instead of an audio post. Do they work with iTunes?

**Comment by m0sa** [comment]
@donkirkby they should work now #130

**Comment by donkirkby** [comment]
Thanks, @m0sa, that problem looks good to me now.

**Comment by hairboat** [comment]
Should be fixed as of https://github.com/StackExchange/stack-blog/commit/ac78fa719f4b0eb80386a0e91a6afcfb3e07f879 (and surrounding commits); everything should be back on iTunes now too. Let me know if this isn't the case.
